### ISSUE TITLE
Handle EAGAIN error

### ISSUE THREAD

**Issue by freehck** [mirage/ocaml-dns#105]
Constantly get this error:

``` ocaml
utop # Dns_resolver_unix.create () >>= fun r -> Dns_resolver_unix.resolve r Packet.Q_IN Packet.Q_A (Name.string_to_domain_name "mail.ru");;
Exception: Protocol.Dns_resolve_error [Unix.Unix_error (Unix.EAGAIN, "recvfrom", "")].
```

My network is fine according to:

``` bash
[root@d011 ~]# dig +short mail.ru
217.69.139.200
94.100.180.201
94.100.180.199
217.69.139.199
```

I suppose that ocaml-dns doesn't know that the right behaviour in case of EAGAIN error is to try reading again after a while.

**Comment by avsm** [comment]
The Lwt version deals with this in #159, so this will no longer happen with 2.0
