### ISSUE TITLE
could mirage tests be using mirage-vnetif?

### ISSUE THREAD

**Issue by yomimono** [mirage/ocaml-dns#106]
The mock network modules in `lib_test/ounit/test_mdns_responder_mirage` have a lot of boilerplate and stubbed-out code.  Could they be replaced by the [mirage-vnetif](https://github.com/magnuss/mirage-vnetif) library, which is intended to provide in-memory network stacks for testing?

**Comment by avsm** [comment]
Since #159 is merged, we don't have any test cases for the mirage- or lwt-specific backends (but extensive tests for the core suite).  Leaving this open for a mirage-vnetif test suite for this library

**Comment by hannesm** [comment]
when adding mirage-vnetif based tests, please investigate first what you like to test... the mirage layer is rather slim (mainly tcp connection management), most of the server and resolver logic can be tested in a pure fashion -- no need for vnetif :)
