### ISSUE TITLE
gethostbyname with socket options

### ISSUE THREAD

**Issue by jerome-arzel** [mirage/ocaml-dns#110]
Hello, is it a simple way to use `Dns_resolver_unix.gethostbyname` but with some modifications on the created socket? For example I want to bind the created socket on a specific address (like -b option in dig), but it seems that I need to rewrote the code written in `Dns_resolver_unix` and use `Dns_resolver` module for that.

Is there a better option to do this?

**Comment by avsm** [comment]
Since #159 is merged, we're actually missing a Lwt resolver in the trunk branch, but it'll be easier to add this requested feature in the 2.x series.

**Comment by hannesm** [comment]
@avsm uhm, there already is https://github.com/mirage/ocaml-dns/blob/master/lwt/client/dns_client_lwt.ml (it's now called client), but there aren't any socket options to be passed at the moment....

**Comment by hannesm** [comment]
this can be achieved by a custom implementation of `Dns_client_flow.S`. If such an implementation (with Lwt? Unix?) turns out to be useful and mature, please PR and we can merge this -- either side-by-side with the existing implementation or as a replacement of the existing implementation.
