### ISSUE TITLE
Cannot decompress name which is a pointer to a pointer

### ISSUE THREAD

**Issue by yeungda-rea** [mirage/ocaml-dns#127]
At my office people are having [an issue](https://github.com/docker/for-mac/issues/1243) with Docker for Mac 1.13.0. It turns out this is due to it's DNS forwarder returning [incorrect results](https://github.com/djs55/ocaml-dns-forward/issues/56) from it's cache. The error in the results is characterised by a name which should be `foo.com.`, but actually is `.` - the root domain. This only happens when the upstream DNS returns an answer containing a name, which is a pointer to a pointer. Information is being lost when the packet is parsed by `ocaml-dns`.

When `ocaml-dns` parses a name which is a pointer to a pointer, it returns a result of no name.

Let's take a look at one of the packets that causes the problem:

```
00000000: 00000000 00000001 10000001 10000000 00000000 00000001  ......
00000006: 00000000 00000010 00000000 00000000 00000000 00000001  ......
0000000c: 00101100 01100011 01101111 01110111 01100010 01100101  ,cowbe
00000012: 01101100 01101100 00101101 01110000 01110010 01101111  ll-pro
00000018: 01100100 00101101 01100100 01101111 01100011 01101011  d-dock
0000001e: 01100101 01110010 00101101 01110010 01100101 01100111  er-reg
00000024: 01101001 01110011 01110100 01110010 01111001 00101101  istry-
0000002a: 01110110 00110010 00101101 01110000 01110010 01101111  v2-pro
00000030: 01100100 00101101 01110011 01110100 01101111 01110010  d-stor
00000036: 01100001 01100111 01100101 00010001 01110011 00110011  age.s3
0000003c: 00101101 01100001 01110000 00101101 01110011 01101111  -ap-so
00000042: 01110101 01110100 01101000 01100101 01100001 01110011  utheas
00000048: 01110100 00101101 00110010 00001001 01100001 01101101  t-2.am
0000004e: 01100001 01111010 01101111 01101110 01100001 01110111  azonaw
00000054: 01110011 00000011 01100011 01101111 01101101 00000000  s.com.
0000005a: 00000000 00000001 00000000 00000001 11000000 00001100  ......
00000060: 00000000 00000101 00000000 00000001 00000000 00000000  ......
00000066: 00000000 00111011 00000000 00000010 11000000 00111001  .;...9
0000006c: 11000000 01101010 00000000 00000001 00000000 00000001  .j....
00000072: 00000000 00000000 00000000 00000100 00000000 00000100  ......
00000078: 00110110 11100111 11111011 00001001 00000000 00000000  6.....
0000007e: 00101001 00001111 10100000 00000000 00000000 00000000  ).....
00000084: 00000000 00000000 00000000                             ...
```

At position 12, there is a sequence of labels:

12: `cowbell-prod-docker-registry-v2-prod-storage`
57: `s3-ap-southeast-2`
75: `amazonaws`
85: `com`

At position 106 there is a pointer to 57:

```
11000000 00111001  .9
```

And at position 108 there is a pointer to 106:

```
11000000 01101010 .j
```

I was hoping to find that section [4.1.4](https://tools.ietf.org/html/rfc1035#section-4.1.4) (message compression) of RFC 1035 would provide some justification for implementing pointers to pointers. Sadly it makes no mention of them.

So I went looking for some DNS test suites and found [this](https://lists.isc.org/pipermail/bind-users/2006-June/062945.html):

> In practice, what BIND does is 'correct'. Or inversely, if you do anything
other than BIND, you are asking for trouble. The RFCs are of secondary
importance, especially where they grant latitude.

and this:

> We mostly validate against BIND and DJBDNS, those being the 'industry standard'.

I can confirm that `dig` and `dnsqr` are able to successfully interpret the pointer to a pointer.  Here's how DJBDNS [does it](https://github.com/abh/djbdns/blob/df36440a03d3aa13996bfc5a0ac87b3a6c0c28d3/dns_packet.c#L35-L77).

@hannesm [notes](https://github.com/djs55/ocaml-dns-forward/issues/56#issuecomment-277989757) that there is a risk if this is implemented without consideration of malicious packets. An acceptable solution should not loop infinitely when encountering a self referential pointer. CERT's [VU#23495](https://www.kb.cert.org/vuls/id/23495) confirms this:

> Numerous DNS implementations do not perform sufficient input checking on compressed labels, allowing an attacker to craft a DNS query containing malformed compressed labels. For example, a packet can be constructed that has a pointer that points back to itself, or that contains a pointer that points to another pointer which points back to the first pointer. When vulnerable programs attempt to decode these malformed labels, various undesirable effects can be induced in the decoding process including allocating all of the process's available memory or causing the process to enter an infinite loop.

Would you be willing to accept a pull request that allows `ocaml-dns` to decompress pointers to pointers? I'm keen to help get this fixed and would be happy to work with you to do so.

**Comment by hannesm** [comment]
@yeungda-rea YES! (and thanks again for the extensive technical report) :)  and while those pointers to pointers are a risk, we can implement it carefully and write some tests to convince ourselves that we do not loop forever.

**Comment by avsm** [comment]
Thank you for the detailed and informative report!  Confirming what @hannesm said -- we can accept and test a pointer-to-pointer parsing strategy along the lines of djbdns indeed.
