### ISSUE TITLE
Name.ml invariants

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-dns#137]
does anyone feel responsible for this library?  I spend last evening reading through `name.ml`, and was wondering about the design decisions made here:
- `type t` is abstract (this is great!)
- `to_key` does some domain name validation (`0 < length < 64` and each character must be non-zero)
- both `of_string` and `of_string_list` (and cons) apply `String.lowercase` (but do no other checks)
- `parse` (rather `parse_label`) does not validate any label content (but by construction restricts size to be correct (0 < length < 64))
- exceptions are thrown all over

Since `t` is abstract, this allows us to specify invariants and check them for construction -- there will never be a `t` which violates these (they could contain the label length, and which ASCII characters may be within a label).  But AFAICS, there are none maintained.

Both `Name.Map` and `Name.Set` use _case-sensitive_ comparison, which is not very convenient if you actually want to use them (DNS labels are specified to be case-insensitive, and clients and servers are free to mutate the case of single characters (e.g. make it all uppercase, or increase entropy by randomly switch the case of characters) - you may want to read through https://developers.google.com/speed/public-dns/docs/security)

The check for domain name fragments in `to_key` is not sufficient: arbitrary control sequences (e.g. ASCII < 0x20) are left in the strings, as well as whitespaces and '.' characters.  I struggle to understand why there is need for both `to_string` and `to_key` (one which uses '.' as separator, the other '\000'). EDIT: see [RFC2181[(https://tools.ietf.org/html/rfc2181) for some clarifications, it is a bit more tricky (valid names for the internet vs valid data in the caching key-value store).

I suspect the authoritative nameserver code is good as it goes since (zone) input is always trusted (threat model does not include to get something bad here), and user questions are looked up in the `trie` data structure (which uses `to_key`, and thus lowercased strings).

To get closer to the RFC, we should preserve the case (of questions. in answers -- a question: A foo.bAr.com should reply with q: foo.bAr.com answer: foo.bAr.com 300 IN|A 1.2.3.4 -- whereas atm the reply is: q: foo.bAr.com answer: foo.bar.com).

Is there anyone working in this direction (or having resources to do so?), or best left as it is, since it is shipped and deployed code which "works for me"?

EDIT: rephrased some paragraphs

**Comment by avsm** [comment]
This is a good issue to raise, as ocaml-dns is a really old library now -- over 11 years old for some of the original code, and it has been through multiple iterations of parsing techniques as our library ecosystem has grown.

To this:
> Is there anyone working in this direction (or having resources to do so?), or best left as it is, since it is shipped and deployed code which "works for me"?

I think the answer needs to split up the build into smaller independent OPAM packages which have more explicit dependencies (so that we can build the core parser with a dependency on Lwt or Async for example).

I would propose:

- remove depopts, make explicit OPAM packages for the parser/printer, the server/client, and the lwt/async/mirage backends. 
- modernise the parser and address the concerns in this PR. @djs55 and @MagnusS are interested in helping with this as they are using the code in docker/vpnkit
- activate fuzz testing of the protocol (probably with @yomimono and @stedolan's magic AFL module)
- fix up revdeps for the new OPAM package scheme and make any API breaking changes as needed in consuming libraries so we're not stuck with older design decisions.

**Comment by djs55** [comment]
I don't feel particularly responsible for this library but I'd like to help if I can. I'd like to see the APIs improved and made more consistent: e.g. perhaps this is a small issue but it bothers me that `Dns.Name.t` (good) but then we have `Dns.Packet.rr` and `Dns.Packet.question` (hm). I was surprised that we had a long-standing bug with decompression of labels to labels. It took me ages to spot that the parser (or was it the printer) was reversing the order of resource records.

Perhaps we should move the server and client (including mirage) code to other places and make this repo solely about the DNS protocol and focus on correctness / RFC compliance?

**Comment by avsm** [comment]
> Perhaps we should move the server and client (including mirage) code to other places and make this repo solely about the DNS protocol and focus on correctness / RFC compliance?

Thanks! I think that in the first instance, rearranging the code within the same Git repository into separate OPAM packages would be good.  We can do repo splits at a later stage.

**Comment by dsheets** [comment]
As mentioned elsewhere (but I can't find it now), I'd really love to see just the domain name handling in a separate library that maintains the invariants you mention, @hannesm. This would also be a great place to implement IDN features (punycode handling, etc). This library, ipaddr, and others could then use just the domain name type without all kinds of other baggage.

**Comment by hannesm** [comment]
NB: there's a Packet.rr and RR.rrset (and Packet.rdata and RR.rdata)... as mentioned on IRC, I took the liberty to extract packet and name from this library, minimise them, and put them into a bit better shape (not yet finished, but a sneak preview of label decompression without hashtables and less loops is [here](https://gist.github.com/hannesm/c6392878751bec2e82abe1e58468dcfa)).

**Comment by avsm** [comment]
@hannesm tempted to try AFL on the label decompression to see it can break it? :-)

**Comment by hannesm** [comment]
@avsm please go ahead ;) (when I understand how to setup afl, I'll give it a try for sure)  the lesson I learned from earlier attempts was that within a compressed domain name there will be no pointer pointing anywhere within this name.  By having `names` being fully expanded I also see no way to introduce cycles (I only allow back pointers, never forward pointers).

**Comment by avsm** [comment]
dns 1.0 sets the scene for fixing some of the issues raised here, including splitting out the domain name handling into a separate package in the future.  So getting there...

**Comment by hannesm** [comment]
now closing this, FWIW, there's https://github.com/roburio/udns now -- which does not separate the dns_name into a separate package.  it uses internally a (reversed) string array instead of a string list (as done in here), leading to ~5x performance improvements.
