### ISSUE TITLE
project setup

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-dns#163]
so we should ensure to
- never push to master (yes, i mean it)
- have proper reviews of any incoming PRs
- and CI testing (only if its green, merge)

we can achieve this by some settings on github AFAICT, but i never did. maybe a CODEOWNERS file is valuable here?

**Comment by avsm** [comment]
Sounds sensible. i've activated protected branches and required reviews. CODEOWNERS needed next and that can be enforced too.

**Comment by hannesm** [comment]
that's sufficiently done afaict
