### ISSUE TITLE
mirage/mirage-server: revise connection management

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-dns#169]
it's pretty ad-hoc atm, what is in general (server/resolver have slightly different use cases) there:
- keep one tcp connection to remote
- keep this interesting tcp connection of remote
- only establish a single tcp connection to each remote (esp. when primary boots up with 10 zones, and has a secondary for all zones -- "block" until tcp session established)
- only keep n tcp connections around at any time

**Comment by avsm** [comment]
This looks like it's generally a useful bit of logic to have in a tcp client somewhere; irmin might need it too for a p2p backend /cc @samoht

**Comment by hannesm** [comment]
addressed in #184.
