### ISSUE TITLE
Glue record for primary DNS server

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-dns#213]
Currently, I used `ocaml-dns` as my primary DNS server (`primary-git`) and use `ns6.gandi.net` as my secondary DNS server. However. if I do nothing (eg. just fill my zone file and launch the DNS server), I got an error:

```
[dns_server] lookup for A ns6.gandi.net returned nothing as well
```

@hannesm gaves me a solution where:
1) put a new entry in my zone file like `ns6.gandi.net. A X.X.X.X`
2) make a new `gandi.net` zone file with `ns6.gandi.net. A X.X.X.X`

does not work:
1) the server told me: `error during loading git an entry of x25519.net is not in its zone, won't handle this`
2) the server told me: `error during loading git text: couldn't find zone gandi.net: not authoritative`

 Currently the solution is to make a new `gandi.net` zone file, write an `SOA` and fill it with `ns6.gandi.net`. It's work but may be it's not the proper way to do that.

**Comment by hannesm** [comment]
thanks for your report.

I implemented a solution for this (putting the ns6.gandi.net address record in your x25519.net zone). the downside is that now the zone file may include non-authoritative data, which needs to be updated (whenever ns6.gandi.net changes their IP address - shouldn't happen too frequently ;)). (see the linked PRs to this repository and roburio/unikernels). please let me know if this works fine for you.

an alternative implementation could use a dns-client to resolve ns6.gandi.net, but I dislike the dependency of the primary authoritative nameserver to a dns-client/resolver.
