### ISSUE TITLE
Error on 32bit architecture

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-dns#234]
I'm not really aware about DNS but the CI got an error about an integer which is larger than what is authorized with 31 bits here: https://github.com/mirage/ocaml-dns/blob/50fe8eef13dd880fb98e84a028440f09bc488827/src/dns.ml#L1545

However, I'm not sure about this line where `flags` seems to be a 16 bits integer, so `dnssec_ok` will be always equal to `false`.

**Comment by hannesm** [comment]
I think you're right and it should be 0x8000 instead.

**Comment by hannesm** [comment]
see #235 for a fix

**Comment by hannesm** [comment]
ref mirage/ocaml-cstruct#78
