### ISSUE TITLE
Controlling dns-client log level independently

### ISSUE THREAD

**Issue by orbitz** [mirage/ocaml-dns#279]
Is it possible to control the log level of dns-client independently.  For my application I do a debug log level by default and then switch components to a higher log level as needed.  I see dns-client has its own log source, but it's not exposed for a log-level setting.

**Comment by hannesm** [comment]
the approach used by e.g. mirage-runtime is:

```OCaml
type log_threshold = [`All | `Src of string] * Logs.level

let set_level ~default l =
  let srcs = Logs.Src.list () in
  let default =
    try snd @@ List.find (function (`All, _) -> true | _ -> false) l
    with Not_found -> default
  in
  Logs.set_level (Some default);
  List.iter (function
      | (`All, _) -> ()
      | (`Src src, level) ->
        try
          let s = List.find (fun s -> Logs.Src.name s = src) srcs in
          Logs.Src.set_level s (Some level)
        with Not_found ->
          Fmt.(pf stdout) "%a %s is not a valid log source.\n%!"
            Fmt.(styled `Yellow string) "Warning:" src
    ) l
```

So, what you can always do is to get all log sources (`Logs.Src.list ()`), pick the one by name (`Logs.Src.name log_source = <what_i_want>`) and set its level (`Logs.Src.set_level log_source (Some Info)`). I have not seen any library that exposes the log source.

**Comment by orbitz** [comment]
Ahhh thank you!
