### ISSUE TITLE
Dns.Packet.parse_rdata incorrectly parses SRV

### ISSUE THREAD

**Issue by infidel** [mirage/ocaml-dns#30]
The code is:

```ocaml
    | RR_SRV ->
        BE.(
          SRV (get_uint16 buf 0, (* prio *)
               get_uint16 buf 2, (* weight *)
               get_uint16 buf 4, (* port *)
               parse_name names (base+6) buf |> stop
          ))
```

But the "base" argument to parse_name is ignored for parsing (it only affects the return value), so it doesn't work. The most obvious fix is to shift the buffer by 6 before passing to parse_name, and that would match most of the other RR types. I can submit a PR to that effect, including a unit test that triggers the bug (preferably after my other PR has been merged).

However, the values passed for "base" are inconsistent and the argument seems to be fairly pointless?

**Comment by dsheets** [comment]
I think this can be closed now as 0.12.0 indicates a fix shipped. Please re-open if this is incorrect.

If fixing something like `base` is the reason this is still open, please open a new issue for just that.
