### ISSUE TITLE
Circular references with `happy-eyeballs.lwt`

### ISSUE THREAD

**Issue by bikallem** [mirage/ocaml-dns#313]
There is a circular reference with `dns-client` package and `happy-eyeballs` package. `dns-client.lwt` depends on `happy-eyeballs` and `happy-eyeballs.lwt` depends on `dns-client.lwt`. Trying to build `happy-eyeballs` results in error (https://github.com/roburio/happy-eyeballs/issues/23).

**Comment by hannesm** [comment]
Thanks for your report. I'll answer in more detail in your happy-eyeballs issue.

**Comment by hannesm** [comment]
For the record, there is no circular dependency on the opam level: dns-client depends on happy-eyeballs; happy-eyeballs-lwt (and happy-eyeballs-mirage) depend on dns-client.
