### ISSUE TITLE
dns-client-mirage dependencies: drop tls (for qubes-mirage-firewall)

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-dns#321]
to make the code smaller, it would be great to find a way to get rid of that dependency (or move that to a subpackage).

**Comment by hannesm** [comment]
the good news is that it is a build-time only dependency in that scenario, since only dns-client is used, not dns-client.mirage.

**Comment by xbc5** [comment]
@hannesm would you consider optional TLS support for Qubes? I don't use the DNS feature for qubes-mirage-firewall (but I'd like to) because it only supports plaintext DNS.

**Comment by hannesm** [comment]
sure, well, in terms of the qubes-mirage-firewall (or the qubes-firewall): the firewall rules may contain "hostname" entries, and that is why the qubes-mirage-firewall needs to be able to resolve hostnames.

The resolution is done by the DNS resolvers provided via QubesDB. Is there a way to specify DoT in qubesdb?

Or how should the setup be? Is there usually a (local) DNS resolver VM? If yes, we could have a qubes-mirage-dns-resolver that receives UDP/TCP on the local side, and uses DoT on the remote side (and the qubes-mirage-firewall could use that as well).

**Comment by hannesm** [comment]
since #331 landed and got released, the dns-client package does not depend on tls anymore. closing this issue.

**Comment by hannesm** [comment]
@xbc5 if you'd like to have dns-over-tls in the qubes-mirage-firewall, please open an issue on that repository :) thanks a lot.
