### ISSUE TITLE
It would be nice to publish the code coverage of the tests to coveralls.io

### ISSUE THREAD

**Issue by infidel** [mirage/ocaml-dns#33]
Like Travis CI, Coveralls is free for open source projects. Here's an example of what it will look like: https://coveralls.io/builds/1645825

If you think it's a good idea then I will submit a patch to .travis-ci.sh that will look similar to this:

https://github.com/infidel/ocaml-mdns/blob/master/.travis-ci.sh#L46

It's a fairly ugly hack at the moment. Some of it is borrowed from: https://github.com/sagotch/ocveralls

If there's an easy way to conditionally add "bisect" to BuildDepends based on whether a configure flag is enabled then I'd love to know. It can't be unconditional because it's performing the actual coverage instrumentation, and isn't just a library.

Presumably this could also be achieved in myocamlbuild.ml too, so if that is the preferred solution then I am willing to spend the time to understand how to do that (looks like black magic so far).

P.S. if mDNS ends up integrated into ocaml-dns then ocaml-mdns can disappear.

**Comment by avsm** [comment]
Just wondering why the patched Bisect is required -- is the upstream maintainer not integrating the patch, or is it a local change?

**Comment by infidel** [comment]
The README for ocveralls says:

```
Xavier Clerc is the author of the Bisect tool. I provide a modified version of Bisect he sent me with his agreement, since he did not released the updated version yet. Archive is available at
bisect.sagotch.fr.
```

This text was added in May 2014, but the last release of bisect was in 2012, so I guess I will submit an issue to ocveralls for clarification.

**Comment by infidel** [comment]
Please see https://github.com/sagotch/ocveralls/issues/2

**Comment by infidel** [comment]
OK, now ocveralls works with an unpatched installation of bisect. Requires OCaml >= 4.02.0.

Use of bisect still requires telling the compiler to use the bisect package though, so suggestions for how to do this without "sed" (or equivalent) are welcome.

**Comment by infidel** [comment]
I saw the link to http://www.hammerlab.org/2015/03/04/creating-ocaml-code-coverage-reports-for-ketrew/ that @avsm tweeted. I didn't get it working yet (conflicts with -syntax), but the theory looks good.

It's a bit of a shame that it requires 50 lines of OCaml code for a solution that is slightly cleaner than using one sed command:

https://github.com/hammerlab/ketrew/blob/bisect_coverage_two/myocamlbuild.ml

**Comment by avsm** [comment]
Yeah, integration with build systems really isn't great right now.

**Comment by infidel** [comment]
OK, I got an example working using myocamlbuild.ml: https://github.com/infidel/ocaml-mdns/blob/master/myocamlbuild.ml

Is this pattern OK for a PR, including coveralls.io?

**Comment by avsm** [comment]
This is now easier with dune since #159 is merged, so i'll add this before the 2.0 release

**Comment by hannesm** [comment]
it is still unclear how to best integrate bisect_ppx into the modern build chain (i don't think depending on an environment variable and having a opam-dependency on bisect_ppx is a good solution). I'll close this for now (since it mostly contains information about the old dns stack and ocamlbuild), please submit a PR whenever there's a decent solution.

**Comment by avsm** [comment]
The critical path for bisect_ppx in a modern build chain will be addressed in https://github.com/ocaml/dune/issues/57
