### ISSUE TITLE
Clarify allocation rules for mirage in Dns.Buf.create

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-dns#42]
When does `alloc` need to be used? When using a pointer to the memory for writing to the network? To a block device?

If `Dns.Buf.create` is being used for other memory or for storage of temporary or received packets in an application, does `alloc` need to be used? Library users need to know the precise semantics for when `alloc` MUST and MAY NOT be passed to `Dns.Buf.create`.

Please put some of this information into the ocamldoc for `Dns.Buf.create`.

**Comment by avsm** [comment]
This used to be for passing through to the underlying Cstruct.create, but that has now removed the alloc option via https://github.com/mirage/ocaml-cstruct/pull/237, so this is definitely no longer needed here since #159 is merged
