### ISSUE TITLE
TC bit and TCP fallback

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-dns#44]
It would be nice to have support for RFC 5966 https://tools.ietf.org/html/rfc5966, DNS-over-TCP, for larger/longer sessions.

The server portions would need to implement connection limits. The client portions would need to pay attention to the `TC` flag. A client should be able to select UDP vs TCP (vs EDNS0) and introspect on requests to discover what was used/tried. This functionality is necessary to perform DNS probing and adapt clients to the local network conditions.

**Comment by infidel** [comment]
For future reference, see also https://tools.ietf.org/html/rfc6762#section-18.5 and other places in the RFC where "TC bit" or "Truncated" is mentioned.

**Comment by heidi-ann** [comment]
Its looking like TCP failback could be quite useful, might this be worth adding as a mirage pioneer project?
https://github.com/mirage/mirage-www/wiki/Pioneer-Projects

**Comment by avsm** [comment]
Since #159 is merged, the Truncated bit is respected and the Lwt client can do TCP requests, but we still need to add support for the server side and connection limiting.

**Comment by hannesm** [comment]
hmm, the client uses tcp by default, yes. the resolver code uses udp by default, and switches to tcp if truncated. the server accepts both udp and tcp (denying axfr/ixfr/update via udp) -- imho this can be closed unless there's a strong use to support udp for the client.
