### ISSUE TITLE
Better EDNS0 control and discovered responder state helpers

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-dns#46]
Right now, clients have no control over EDNS0 https://tools.ietf.org/html/rfc2671 requests and the special requests that are made with EDNS0 turned on uniformly set the UDP packet reassembly size to 1500 (which is too large for most ethernet networks without IP fragmentation due to headers).

Client control/exposure of EDNS0 should be improved and functions introduced that help clients maintain discovered responder/network state for setting EDNS0 parameters or selecting TCP fallback.

**Comment by avsm** [comment]
clients since #159 can now specify Edns options explicitly
