### ISSUE TITLE
Expose Dns_resolver.send_pkt functionality

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-dns#47]
Users should be able to construct custom packet to be sent rather than having to effectively use `Dns_resolver.resolve` as a packet constructor. This is probably necessary to give fine control over EDNS0 (#46) without cramming all packet construction parameters into a resolve call.

This would also benefit forwarders (which may wish to inspect/re-write a packet and then re-send).

Opinions?

**Comment by avsm** [comment]
Yep, with a better than than send_pkt

**Comment by dsheets** [comment]
Related to #20.

**Comment by dsheets** [comment]
I think this is covered by #49. Closing.
