### ISSUE TITLE
Different QNAME encoding

### ISSUE THREAD

**Issue by heidi-ann** [mirage/ocaml-dns#51]
I've got two unikernels, one users gethostbyname and the other uses resolve. For the same query and server, the gethostbyname one works and the other doesnot (fails with no such name). On closer inspected, the only difference between the DNS query packets is the same domain name has been encoded differently in the QNAME field. I'll add an image with the two encoding in a sec

**Comment by heidi-ann** [comment]
![screen shot 2015-02-17 at 17 18 16](https://cloud.githubusercontent.com/assets/1835251/6233231/5da75594-b6c9-11e4-82cc-f04a6b7dcf48.png)

**Comment by dsheets** [comment]
The top packet has `google.com` as a single label (wrong) whereas the bottom packet has `google` followed by `com` (correct).

**Comment by dsheets** [comment]
I think this is probably because your `resolve` call is using `["google.com"]` when it should be using `["google";"com"]`.

**Comment by heidi-ann** [comment]
yes, I think thats it. thanks david :)

**Comment by heidi-ann** [comment]
for future peoples ref: string_to_domain implements this

**Comment by avsm** [comment]
Could you file another issue here to make this API safer?  We should protect the `resolve` call behind an abstract type that guarantees this invariant of splitting up a domain name into label chunks.

**Comment by heidi-ann** [comment]
working on PR as we speak
