### ISSUE TITLE
Travis script producing > 10000 lines of console output

### ISSUE THREAD

**Issue by heidi-ann** [mirage/ocaml-dns#54]
Can we reduce to the verbosity of output from the travis scripts (e.g. turn off some warnings), as travis will only provide the first 10000 lines of console output so I can't see why a build has failed

**Comment by infidel** [comment]
As a work-around, I found that there is a "Download Log" button in the top-right of the Travis page, which avoids the length limit. For example it links to:

https://api.travis-ci.org/jobs/51347579/log.txt?deansi=true

**Comment by dsheets** [comment]
This is annoying but the work-around is sufficient for now. If it starts being a significant problem, we should re-open this issue.

**Comment by Natim** [comment]
I think it shouldn't stop at 10000 lines if we are looking at it/streaming logs from the beginning but it should if we arrive on the logs page later.
