### ISSUE TITLE
exception Failure("not found") from use of eventual_process_of_zonefiles

### ISSUE THREAD

**Issue by heidi-ann** [mirage/ocaml-dns#57]
I'm having difficulties using eventual_process_of_zonefiles directly instead of via processor_of_zonefiles. The code is below, lwt is throwing ```Fatal error: exception Failure("not found")```, any general advise on debugging this class of errors would also be appreciated?

unikernel.ml
```
open Lwt
open V1_LWT
open Dns
open Dns_server

let port = 53
let zonefile = "test.zone"
let resolver_addr = Ipaddr.V4.make 8 8 8 8
let resolver_port = 53

module Main (C:CONSOLE) (K:KV_RO) (S:STACKV4) = struct

  module U = S.UDPV4
  module DS = Dns_server_mirage.Make(K)(S)
  module DR = Dns_resolver_mirage.Make(OS.Time)(S)

  let process resolver c zoner ~src ~dst packet =
      let open Packet in
      C.log_s c (to_string packet) 
      >>= fun () ->
      zoner ~src ~dst packet 
      >>= fun answer ->
      match answer with
      | Some a -> return answer 
      | None -> 
          match packet.questions with
          | [q] -> 
              DR.resolve (module Dns.Protocol.Client) resolver resolver_addr resolver_port q.q_class q.q_type q.q_name 
              >>= fun result ->
              (C.log_s c (to_string result) >>= fun () ->
              return (Some (Dns.Query.answer_of_response result))) 
          | _ -> return None


  let start c k s =
    let server = DS.create s k in
    let resolver = DR.create s in
    DS.eventual_process_of_zonefiles server [zonefile]
    >>= fun zoner ->
    let processor = (processor_of_process (process resolver c zoner) :> (module Dns_server.PROCESSOR)) in 
    DS.serve_with_processor server ~port ~processor
end
```

This issues is in the use of eventual_process_of_zonefiles, the error throw is below:

```
Fatal error: exception Failure("not found")
Raised at file "src/core/lwt.ml", line 788, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 127, characters 2-35
```

**Comment by infidel** [comment]
It seems very likely that the code in eventual_process_of_zonefiles that handles the failure of KV_RO.size is the source of the exception:

https://github.com/mirage/ocaml-dns/blob/master/mirage/dns_server_mirage.ml#L47

If you are not convinced of that then modify the "not found" message to be more specific. If this turns out to be true then clearly the stack trace is misleading. The manual mentions that this is unfortunately to be expected: https://ocsigen.org/lwt/manual/

```
When using Lwt, exceptions are not recorded by the ocaml runtime, and so you don't get backtraces. However it is possible to get them when using the syntax extension. All you have to do is to pass the -lwt-debug switch to camlp4:

$ ocamlfind ocamlc -syntax camlp4o -package lwt.syntax \
    -ppopt -lwt-debug -linkpkg -o foo foo.ml
```

I'm not sure how to do that though.

For this specific bug though, think about: What is in your config.ml? What command are you using to run the unikernel, and what is the current working directory? Where is test.zone?

**Comment by heidi-ann** [comment]
Thank you so much @infidel 

I combination of removing and readding the test.zone from data and clean up the build seem to fix this. It there a reason why we use throw "not found" instead a more specific error like "error finding file" ?

**Comment by infidel** [comment]
A more specific error message would indeed be useful. As to the reason, you would need to ask the author of that line of code, who could be found through the "blame" link at the top right of the GitHub page that I linked above (or the command line equivalent).

As far as additional debugging advice, when the more convenient tools like stack traces don't help, the old fashioned method of inserting "printf" statements at selected locations is sometimes the only option, at least for me.

**Comment by heidi-ann** [comment]
thanks @infidel, closing issue

**Comment by avsm** [comment]
Reopening this -- we should fix the use of Not_found to be more informative.
