### ISSUE TITLE
release with cstruct-1.6.0 support

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-dns#68]
it would be nice to have a release which allows to use cstruct-1.6.0...

**Comment by infidel** [comment]
What's the problem with it?

**Comment by hannesm** [comment]
there's no problem - afaics @dsheets fixed master for new cstruct already... just that I have libraries which need `cstruct >= 1.6.0` and thus I end up in lots of recompilations to downgrade and upgrade all the libraries using cstruct

**Comment by infidel** [comment]
Oh, sorry, that makes sense.

**Comment by avsm** [comment]
@dsheets, leaving this one to you as you've been doing most of the merging.

**Comment by dsheets** [comment]
This is in the pipe as #71. We now require uri 1.9 for the service name registry and mirage/ocaml-uri#74 tracks that disaggregation.

**Comment by dsheets** [comment]
In the end, only uri 1.7.0+ was required. `dns.0.15.0` has been released in ocaml/opam-repository#4092.
