### ISSUE TITLE
Separate type for PQDNs?

### ISSUE THREAD

**Issue by infidel** [mirage/ocaml-dns#81]
Most parts of this package assume that Name.t always refers to a fully-qualified domain name, which I think is correct because you can't have a partially-qualified domain name in a DNS packet, or in a (parsed) zone.

Name.to_string is a little inconsistent with this idea though by not appending a dot, and the comments on of_string acknowledge this. This inconsistency is probably the root cause of https://github.com/mirage/ocaml-ipaddr/issues/53

A few places such as the flavours of gethostbyname could benefit from the ability to represent FQDNs and PQDNs a separate types and convert between them. If gethostbyname parsed the string into a different type depending on whether there was a trailing dot then the Unix version could make use of search_domains, which seems to be unused at the moment. What do you think?

**Comment by dsheets** [comment]
I think we need an IDN library.

**Comment by hannesm** [comment]
I agree, a standalone IDN library would be really useful to have!

**Comment by avsm** [comment]
@hannesm is this something for the domain-name library, or here?

**Comment by hannesm** [comment]
yes, it turns out https://hannesm.github.io/domain-name/doc/domain-name/Domain_name/index.html#val-to_string already supports `?trailing` -- whether to append a final `.` or not.
